### ISSUE TITLE
ExpandableLayout中可以加入其它布局么

### ISSUE THREAD

**Issue by duanjibin** [shellljx/ExpandableLayout#2]
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/activity_main"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context="com.licrafter.sample.MainActivity">

    <ScrollView
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:orientation="vertical">

            <com.licrafter.exp.ExpandableHeader
                android:id="@+id/exp_header"
                android:layout_width="match_parent"
                android:layout_height="wrap_content">

                <android.support.v4.view.ViewPager
                    android:id="@+id/viewPager"
                    android:layout_width="match_parent"
                    android:layout_height="match_parent" />
            </com.licrafter.exp.ExpandableHeader>

            <com.licrafter.exp.ExpandableLayout
                android:id="@+id/exp_layout"
                android:layout_width="match_parent"
                android:layout_height="wrap_content">

                <TextView
                    android:layout_width="match_parent"
                    android:layout_height="800dp"
                    android:text="你好" />
            </com.licrafter.exp.ExpandableLayout>
        </LinearLayout>
    </ScrollView>
</LinearLayout>
ExpandableHeader显示了 两个图片的高度 请问什么原因呢  可以方便留一下QQ么 进一步的 学习

**Comment by shellljx** [comment]
1057645164

**Comment by shellljx** [comment]
ExpandableLayout的子view必须是（AdapterView，RecyclerView,ScrollView,WebView)之一，ExpandableLayout和ExpandableHeader的父布局必须是一个FrameLayout
