### ISSUE TITLE
大神，怎么不能滑动啊，viewpage

### ISSUE THREAD

**Issue by bensonX** [shellljx/ExpandableLayout#3]

**Comment by shellljx** [comment]
??什么场景下不能滑动？这个demo?

**Comment by bensonX** [comment]
public static void initRepo() {
        data.add(new ImageModel("http://ci.xiaohongshu.com/2cc966e2-eed0-455c-be10-e1377a99b73c@r_1280w_1280h.jpg", 1280, 1280));
        data.add(new ImageModel("http://ci.xiaohongshu.com/c09d083b-2464-4cbe-9219-5210edaff64e@r_1280w_1280h.jpg", 960, 1280));
        data.add(new ImageModel("http://ci.xiaohongshu.com/206222a6-2de4-40f4-a002-654968478e59@r_1280w_1280h.jpg", 1024, 1280);
    }   viewpage 3个图片，无法左右滑动，但看你的视频是可以的（什么都没动，就把这个注释取消了）

**Comment by bensonX** [comment]
可以了， public int getCount() {
            return 1;
        }这个地方没改
